/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Aplication.java
 *
 * Created on 06/09/2013, 21:37:32
 */
package Window;

import Code.Book;
import Code.User;
import System.Lendbook;
import java.awt.event.ActionEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author joseph
 */
public class Aplication extends SwitchablePanel {
    private List<Book> searchList = new ArrayList();
    private List<Book> searchListAcervo = new ArrayList();
    private List<User> searchListUsers = new ArrayList();
    private Book bookEditable;
    /** Creates new form Aplication */
    public Aplication(Window frame){
        super(frame);
        initComponents();
        setDados();
        changeEnable(false);
        succeededDataUpdateMessage.setVisible(false);
        profileBook.setVisible(false);
        saveData.setVisible(false);
        setAcervoData();
        setAcervoUser();
        
     
    }
    


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        searchType = new javax.swing.ButtonGroup();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jPopupMenu3 = new javax.swing.JPopupMenu();
        upToolbar = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        back = new javax.swing.JButton();
        getnome = new javax.swing.JLabel();
        welcome = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        profile = new javax.swing.JTabbedPane();
        searchTab = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        title = new javax.swing.JRadioButton();
        author = new javax.swing.JRadioButton();
        gender = new javax.swing.JRadioButton();
        ISBN = new javax.swing.JRadioButton();
        search = new javax.swing.JButton();
        inputSearch = new javax.swing.JTextField();
        profileBook = new javax.swing.JPanel();
        titleB = new javax.swing.JLabel();
        boxTitle = new javax.swing.JTextField();
        authorB = new javax.swing.JLabel();
        boxAuthor = new javax.swing.JTextField();
        generB = new javax.swing.JLabel();
        boxGener = new javax.swing.JTextField();
        isbnB = new javax.swing.JLabel();
        boxIsbn = new javax.swing.JTextField();
        localBook = new javax.swing.JLabel();
        localB = new javax.swing.JLabel();
        teacherBook = new javax.swing.JLabel();
        teacherB = new javax.swing.JLabel();
        imageBook = new javax.swing.JLabel();
        localBook1 = new javax.swing.JLabel();
        okayOff = new javax.swing.JLabel();
        cancelOn = new javax.swing.JLabel();
        okayOn = new javax.swing.JLabel();
        cancelOff = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        changeData = new javax.swing.JButton();
        saveData = new javax.swing.JButton();
        getBookToMe = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        searchResults = new javax.swing.JList();
        userProfileTab = new javax.swing.JPanel();
        JName = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        JBlocoSala = new javax.swing.JLabel();
        block = new javax.swing.JTextField();
        room = new javax.swing.JTextField();
        JEmail = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        password = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        newPassword = new javax.swing.JTextField();
        saveButton = new javax.swing.JButton();
        succeededDataUpdateMessage = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        searchResultsUsers = new javax.swing.JList();
        jLabel3 = new javax.swing.JLabel();
        acervoTab = new javax.swing.JPanel();
        acervo = new javax.swing.JScrollPane();
        searchResultsAcervo = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        upToolbar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        upToolbar.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                upToolbarAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        upToolbar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        upToolbar.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 43, -1, -1));

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/sair.png"))); // NOI18N
        back.setPreferredSize(new java.awt.Dimension(34, 30));
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        upToolbar.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(717, 3, 60, 50));

        getnome.setFont(new java.awt.Font("Waree", 1, 20));
        getnome.setForeground(new java.awt.Color(0, 0, 140));
        getnome.setText(getNameUser());
        upToolbar.add(getnome, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 15, 257, -1));

        welcome.setFont(new java.awt.Font("Waree", 1, 20));
        welcome.setForeground(new java.awt.Color(0, 0, 140));
        welcome.setText("Olá! Bem-vindo(a),  ");
        welcome.setAlignmentY(0.0F);
        upToolbar.add(welcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 15, -1, -1));

        jButton2.setFont(new java.awt.Font("Ubuntu", 1, 15));
        jButton2.setForeground(new java.awt.Color(28, 83, 191));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/addbook.png"))); // NOI18N
        jButton2.setText("Cadastrar livro");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        upToolbar.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 3, 180, 50));

        add(upToolbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 780, 60));

        profile.setBorder(null);
        profile.setFont(new java.awt.Font("Waree", 1, 15)); // NOI18N

        searchTab.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setLayout(new java.awt.GridLayout(1, 0));

        searchType.add(title);
        title.setText("Título");
        title.setName(""); // NOI18N
        title.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                titleActionPerformed(evt);
            }
        });
        jPanel6.add(title);

        searchType.add(author);
        author.setText("Autor");
        author.setToolTipText("");
        author.setName(""); // NOI18N
        jPanel6.add(author);

        searchType.add(gender);
        gender.setText("Gênero");
        gender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderActionPerformed(evt);
            }
        });
        jPanel6.add(gender);

        searchType.add(ISBN);
        ISBN.setText("ISBN");
        jPanel6.add(ISBN);

        searchTab.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 690, 30));

        search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/lupa.png"))); // NOI18N
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        searchTab.add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 10, 50, 30));

        inputSearch.setFont(new java.awt.Font("Ubuntu", 0, 16));
        inputSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputSearchActionPerformed(evt);
            }
        });
        inputSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputSearchKeyTyped(evt);
            }
        });
        searchTab.add(inputSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 600, -1));

        profileBook.setBackground(new java.awt.Color(255, 255, 255));
        profileBook.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));
        profileBook.setForeground(new java.awt.Color(254, 247, 247));
        profileBook.setToolTipText("");
        profileBook.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        profileBook.setInheritsPopupMenu(true);
        profileBook.setLayout(null);

        titleB.setFont(new java.awt.Font("Ubuntu", 1, 16));
        titleB.setText("Título: ");
        profileBook.add(titleB);
        titleB.setBounds(200, 40, 70, 30);
        profileBook.add(boxTitle);
        boxTitle.setBounds(280, 40, 360, 28);

        authorB.setFont(new java.awt.Font("Ubuntu", 1, 16));
        authorB.setText("Autor:");
        profileBook.add(authorB);
        authorB.setBounds(200, 80, 70, 30);
        profileBook.add(boxAuthor);
        boxAuthor.setBounds(280, 80, 360, 28);

        generB.setFont(new java.awt.Font("Ubuntu", 1, 16));
        generB.setText("Gênero:");
        profileBook.add(generB);
        generB.setBounds(200, 120, 70, 30);
        profileBook.add(boxGener);
        boxGener.setBounds(280, 120, 360, 28);

        isbnB.setFont(new java.awt.Font("Ubuntu", 1, 16));
        isbnB.setText("ISBN:");
        profileBook.add(isbnB);
        isbnB.setBounds(200, 160, 70, 30);
        profileBook.add(boxIsbn);
        boxIsbn.setBounds(280, 160, 250, 28);

        localBook.setFont(new java.awt.Font("Ubuntu", 1, 16));
        localBook.setText("Localização: ");
        profileBook.add(localBook);
        localBook.setBounds(410, 200, 110, 30);
        profileBook.add(localB);
        localB.setBounds(510, 200, 110, 30);

        teacherBook.setFont(new java.awt.Font("Ubuntu", 1, 16));
        teacherBook.setText("Professor: ");
        profileBook.add(teacherBook);
        teacherBook.setBounds(410, 230, 90, 30);
        profileBook.add(teacherB);
        teacherB.setBounds(510, 230, 110, 30);

        imageBook.setBackground(new java.awt.Color(200, 190, 190));
        imageBook.setForeground(new java.awt.Color(125, 141, 147));
        profileBook.add(imageBook);
        imageBook.setBounds(30, 40, 140, 160);

        localBook1.setFont(new java.awt.Font("Ubuntu", 1, 16));
        localBook1.setText("Localização: ");
        profileBook.add(localBook1);
        localBook1.setBounds(410, 200, 110, 30);

        okayOff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/okOK2.png"))); // NOI18N
        profileBook.add(okayOff);
        okayOff.setBounds(69, 200, 30, 30);

        cancelOn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/CancelC.png"))); // NOI18N
        cancelOn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelOnMouseClicked(evt);
            }
        });
        profileBook.add(cancelOn);
        cancelOn.setBounds(10, 200, 30, 30);

        okayOn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/okOK.png"))); // NOI18N
        okayOn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                okayOnMouseClicked(evt);
            }
        });
        profileBook.add(okayOn);
        okayOn.setBounds(69, 200, 30, 30);

        cancelOff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/CancelC 2.png"))); // NOI18N
        profileBook.add(cancelOff);
        cancelOff.setBounds(10, 200, 30, 30);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/closeButton.png"))); // NOI18N
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        profileBook.add(jLabel9);
        jLabel9.setBounds(650, 10, 30, 24);

        changeData.setText("Alterar dados");
        changeData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeDataActionPerformed(evt);
            }
        });
        profileBook.add(changeData);
        changeData.setBounds(190, 210, 130, 30);

        saveData.setText("Salvar");
        saveData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveDataActionPerformed(evt);
            }
        });
        profileBook.add(saveData);
        saveData.setBounds(190, 240, 130, 30);

        getBookToMe.setText("Pegar");
        getBookToMe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getBookToMeActionPerformed(evt);
            }
        });
        profileBook.add(getBookToMe);
        getBookToMe.setBounds(20, 240, 80, 30);

        searchTab.add(profileBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 680, 280));

        searchResults.setFont(new java.awt.Font("DejaVu Sans", 1, 16));
        searchResults.setModel(new javax.swing.AbstractListModel() {
            String[] strings = setListInSearchResult();
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        searchResults.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchResultsMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(searchResults);

        searchTab.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 720, 320));

        profile.addTab("     Busca     ", null, searchTab, "");

        userProfileTab.setForeground(new java.awt.Color(0, 0, 140));
        userProfileTab.setToolTipText("");
        userProfileTab.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JName.setFont(new java.awt.Font("Ubuntu", 1, 16));
        JName.setForeground(new java.awt.Color(0, 0, 140));
        JName.setText("Nome: ");
        userProfileTab.add(JName, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 60, 30));

        name.setFont(new java.awt.Font("Ubuntu", 0, 16));
        userProfileTab.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 340, -1));

        JBlocoSala.setFont(new java.awt.Font("Ubuntu", 1, 16));
        JBlocoSala.setForeground(new java.awt.Color(0, 0, 140));
        JBlocoSala.setText("Bloco / Sala:");
        userProfileTab.add(JBlocoSala, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 120, 30));

        block.setFont(new java.awt.Font("Ubuntu", 0, 16));
        userProfileTab.add(block, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 50, -1));

        room.setFont(new java.awt.Font("Ubuntu", 0, 16));
        room.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomActionPerformed(evt);
            }
        });
        userProfileTab.add(room, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 50, -1));

        JEmail.setFont(new java.awt.Font("Ubuntu", 1, 16));
        JEmail.setForeground(new java.awt.Color(0, 0, 140));
        JEmail.setText("E-mail: ");
        userProfileTab.add(JEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, 30));

        email.setFont(new java.awt.Font("Ubuntu", 0, 16));
        email.setEnabled(false);
        userProfileTab.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 340, -1));

        jButton1.setFont(new java.awt.Font("Ubuntu", 1, 15));
        jButton1.setForeground(new java.awt.Color(0, 0, 140));
        jButton1.setText("Alterar Dados");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        userProfileTab.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, -1, -1));

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 16));
        jLabel2.setForeground(new java.awt.Color(0, 0, 140));
        jLabel2.setText("Senha Atual:");
        userProfileTab.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });
        userProfileTab.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 140, -1));

        jLabel4.setFont(new java.awt.Font("Ubuntu", 1, 16));
        jLabel4.setForeground(new java.awt.Color(0, 0, 140));
        jLabel4.setText("Nova Senha: ");
        userProfileTab.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, 30));
        userProfileTab.add(newPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, 130, -1));

        saveButton.setFont(new java.awt.Font("Ubuntu", 1, 15));
        saveButton.setForeground(new java.awt.Color(0, 0, 140));
        saveButton.setText("Salvar");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });
        userProfileTab.add(saveButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 380, -1, -1));

        succeededDataUpdateMessage.setFont(new java.awt.Font("Ubuntu", 1, 15));
        succeededDataUpdateMessage.setForeground(new java.awt.Color(46, 180, 72));
        succeededDataUpdateMessage.setText("Dados alterados com sucesso!");
        userProfileTab.add(succeededDataUpdateMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 350, -1, -1));

        jButton3.setFont(new java.awt.Font("Ubuntu", 1, 15));
        jButton3.setForeground(new java.awt.Color(0, 0, 140));
        jButton3.setText("Excluir Conta");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        userProfileTab.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 380, -1, -1));

        searchResultsUsers.setModel(new javax.swing.AbstractListModel() {
            String[] strings = setListInSearchResultuser();
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(searchResultsUsers);

        userProfileTab.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 70, 200, 230));

        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 15));
        jLabel3.setForeground(new java.awt.Color(0, 0, 140));
        jLabel3.setText("Usuários Cadastrados:");
        userProfileTab.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 40, -1, -1));

        profile.addTab("Perfil do Usuário", userProfileTab);

        acervoTab.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        searchResultsAcervo.setFont(new java.awt.Font("DejaVu Sans", 1, 16)); // NOI18N
        searchResultsAcervo.setModel(new javax.swing.AbstractListModel() {
            String[] strings = setListInSearchResultAcervo();
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        searchResultsAcervo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchResultsAcervoMouseClicked(evt);
            }
        });
        acervo.setViewportView(searchResultsAcervo);

        acervoTab.add(acervo, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 5, 740, 420));

        profile.addTab("Acervo", acervoTab);

        add(profile, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 780, 490));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/program.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void upToolbarAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_upToolbarAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_upToolbarAncestorAdded

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        goToHome();
    }//GEN-LAST:event_backActionPerformed

    private void titleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_titleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_titleActionPerformed

    private void modelAuxSet(){
        searchResults.setModel(new javax.swing.AbstractListModel() {
                String[] strings = setListInSearchResult();
                public int getSize() { return strings.length; }
                public Object getElementAt(int i) { return strings[i]; }
            });        
    }
    private void searchActionPerformed(java.awt.event.ActionEvent evt) {                                       
        if(!getRadButtonSelect().equals("0")){
            searchList = Lendbook.system.getController().bookSearch(inputSearch.getText(), getRadButtonSelect());
            modelAuxSet();
        }
        else{
            JOptionPane.showMessageDialog(this,"Selecione uma opção de pesquisa");
        }        
    }                                     

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        changeEnable(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      getMainFrame().switchPanels(new BookRegister(getMainFrame()));
    }//GEN-LAST:event_jButton2ActionPerformed

    private void inputSearchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputSearchKeyTyped
        if(!getRadButtonSelect().equals("0")){
            searchList = Lendbook.system.getController().bookSearch(inputSearch.getText(), getRadButtonSelect());
            modelAuxSet();
        }
        else{
            JOptionPane.showMessageDialog(this,"Selecione uma opção de pesquisa");
        }
    }//GEN-LAST:event_inputSearchKeyTyped
    private void inputSearchActionPerformed(java.awt.event.ActionEvent evt){
              
    }
    private void roomActionPerformed(java.awt.event.ActionEvent evt){
              
    }
    private void passwordActionPerformed(java.awt.event.ActionEvent evt){
              
    }
    private void searchResultsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchResultsMouseClicked
            
        if (evt.getClickCount() > 1) {
            changeEnableBooks(false);
            saveButton.setVisible(false);
            String[] aux = ((String) (searchResults.getSelectedValue())).split(" - ");
            List<Book> bookList = Lendbook.system.getController().bookSearch(aux[0], "id");      
            
            Book book = bookList.get(0);
            bookEditable = book;
            inputDadosBook(book);
            changeVisibleButtons(book);
            if (!(Lendbook.user.getEmail().equals(book.getOwner()))) {
                changeData.setVisible(false);
            }else{
                changeData.setVisible(true);                
            }
            
            profileBook.setVisible(true);
            
        }  
    }//GEN-LAST:event_searchResultsMouseClicked

   

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        setValues();
    }//GEN-LAST:event_saveButtonActionPerformed

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked

        profileBook.setVisible(false);
    }//GEN-LAST:event_jLabel9MouseClicked

    private void changeDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeDataActionPerformed

        saveData.setVisible(true);
        changeEnableBooks(true);
        
    }//GEN-LAST:event_changeDataActionPerformed

    private void genderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genderActionPerformed

    private void saveDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveDataActionPerformed

        setDadosBook();
    }//GEN-LAST:event_saveDataActionPerformed

    private void okayOnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_okayOnMouseClicked
            
    }//GEN-LAST:event_okayOnMouseClicked

    private void cancelOnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelOnMouseClicked

        int reply;
        if((Lendbook.user.getEmail().equals(bookEditable.getOwner()))){
            reply = JOptionPane.showConfirmDialog(null, "Deseja realmente disponibilizar este livro para seus coleguinhas?", "Confirmação", JOptionPane.YES_NO_OPTION);
            if(reply == JOptionPane.YES_OPTION){
                bookEditable.changeStatus();
                changeVisibleButtons(bookEditable);
                }
            
        }
        
        
    }//GEN-LAST:event_cancelOnMouseClicked

    private void getBookToMeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getBookToMeActionPerformed

        //Get book avaliable
        int reply;
        reply = JOptionPane.showConfirmDialog(null, "Deseja realmente pegar este livro do seu coleguinha?", "Confirmação", JOptionPane.YES_NO_OPTION);
        if(reply == JOptionPane.YES_OPTION){
            bookEditable.setOwner(Lendbook.user.getEmail());
            bookEditable.changeStatus();
            changeVisibleButtons(bookEditable);
            inputDadosBook(bookEditable);
        }
        
    }//GEN-LAST:event_getBookToMeActionPerformed

    private void searchResultsAcervoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchResultsAcervoMouseClicked

        if (evt.getClickCount() > 1) {
            JOptionPane.showMessageDialog(null, "Para visualizar e alterar suas informações use a aba de pesquisa.");               
        }
    }//GEN-LAST:event_searchResultsAcervoMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       int reply;
       reply = JOptionPane.showConfirmDialog(null, "Deseja realmente deletar sua conta?", "Confirmação", JOptionPane.YES_NO_OPTION);
       if(reply == JOptionPane.YES_OPTION){
           Lendbook.system.remove(Lendbook.user);
           goToHome();
           }
    }//GEN-LAST:event_jButton3ActionPerformed
    private void goToHome(){
        getMainFrame().switchPanels(new Home(getMainFrame()));        
    }
    public String getNameUser(){
          return Lendbook.user.getName();
    }
    private String getRadButtonSelect(){
        if (title.isSelected())
            return "title";
        else if(author.isSelected())
            return "author";
        else if(ISBN.isSelected())
            return "isbn";
        else if(gender.isSelected())
            return "gender";
        else
            return "0";
    }
    
    private String[] setListInSearchResult(){
        int i = 0;
        String[] list;
        if (searchList == null) {
            list = new String[1];                        
        }
        else{
            list = new String[searchList.size()];
        }
        
        for (Book book : searchList) {
            list[i] = book.getID()+" - "+book.getName()+" - "+book.getISBN();
            i++;            
        }
        return list;
    }
    
    private void inputDadosBook(Book book){
        User user = Lendbook.system.getController().userSearch(book.getOwner());
        boxTitle.setText(book.getName());
        boxAuthor.setText(book.getAuthor());
        boxGener.setText(book.getGender());
        boxIsbn.setText(book.getISBN()+"");
        localB.setText(user.getBlock()+" / "+user.getRoom());
        teacherB.setText(user.getName());
    }
    
    private void changeEnableBooks(boolean change){
        boxTitle.setEnabled(change);
        boxAuthor.setEnabled(change);
        boxGener.setEnabled(change);
        boxIsbn.setEnabled(change);
        
    }
    
    private void setDados(){
        name.setText(Lendbook.user.getName() + " " + Lendbook.user.getSurname());
        block.setText(Lendbook.user.getBlock());
        room.setText(Lendbook.user.getRoom());
        email.setText(Lendbook.user.getEmail());
    }
    
    private void setDadosBook(){
        bookEditable.setName(boxTitle.getText());
        bookEditable.setAuthor(boxAuthor.getText());
        bookEditable.setGender(boxGener.getText());
        bookEditable.setISBN(Integer.parseInt(boxIsbn.getText()));
        changeEnableBooks(false);
        saveData.setVisible(false);
        
    }
    
    private void changeEnable(boolean change){
        name.setEnabled(change);
        block.setEnabled(change);
        room.setEnabled(change);
        password.setEnabled(change);
        
        saveButton.setVisible(change);
        
        newPassword.setEnabled(change);
        
        saveButton.setEnabled(change);
           
    }
    private void setValues(){
        boolean save = true;
        try{
            Lendbook.user.setName(splitName()[0]);
            Lendbook.user.setSurname(splitName()[1]);
            Lendbook.user.setRoom(room.getText());
            Lendbook.user.setBlock(block.getText());
            
            if(password.getText().length() != 0)
                if(password.getText().equals(Lendbook.user.getPassword()))
                    Lendbook.user.setPassword(newPassword.getText());
                else{
                    save = false;
                    JOptionPane.showMessageDialog(this, "A senha original não confere.");
                }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        
        
        succeededDataUpdateMessage.setVisible(save);
        
        password.setText("");
        newPassword.setText("");
        
        changeEnable(false);
    }
    
    private String[] splitName(){
        String names[] = {"",""};
        int nameIndex = 0;
        for (int i = 0; i< name.getText().length(); i++) {
            if ((name.getText().charAt(i)) == ' ')
                nameIndex = 1;
            names[nameIndex] += name.getText().charAt(i);
        }
        return names;
    }
    
    private void changeVisibleButtons(Book book){
        if(book.getStatus().equals(Book.OFF)){
            cancelOn.setVisible(true);
            cancelOff.setVisible(false);
            okayOff.setVisible(true);
            okayOn.setVisible(false);
            getBookToMe.setVisible(false);
        }
        else{
            cancelOn.setVisible(false);
            cancelOff.setVisible(true);
            okayOff.setVisible(false);
            okayOn.setVisible(true);
            getBookToMe.setVisible(true);
        }
    }
    
    private void setAcervoData(){
        searchListAcervo = Lendbook.system.getController().bookSearch(Lendbook.user.getEmail(),"owner");
        modelAuxSetAcervo();
        
    }
    
    private void modelAuxSetAcervo(){
        
        searchResultsAcervo.setModel(new javax.swing.AbstractListModel() {
            String[] strings = setListInSearchResultAcervo();
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
            });        
    }
    
    private String[] setListInSearchResultAcervo(){
        int i = 0;
        String[] list;
        if (searchListAcervo == null) {
            list = new String[1];                        
        }
        else{
            list = new String[searchListAcervo.size()];
        }
        
        for (Book book : searchListAcervo) {
            list[i] = book.getID()+" - "+book.getName()+" - "+book.getISBN();
            i++;            
        }
        return list;
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton ISBN;
    private javax.swing.JLabel JBlocoSala;
    private javax.swing.JLabel JEmail;
    private javax.swing.JLabel JName;
    private javax.swing.JScrollPane acervo;
    private javax.swing.JPanel acervoTab;
    private javax.swing.JRadioButton author;
    private javax.swing.JLabel authorB;
    private javax.swing.JButton back;
    private javax.swing.JTextField block;
    private javax.swing.JTextField boxAuthor;
    private javax.swing.JTextField boxGener;
    private javax.swing.JTextField boxIsbn;
    private javax.swing.JTextField boxTitle;
    private javax.swing.JLabel cancelOff;
    private javax.swing.JLabel cancelOn;
    private javax.swing.JButton changeData;
    private javax.swing.JTextField email;
    private javax.swing.JRadioButton gender;
    private javax.swing.JLabel generB;
    private javax.swing.JButton getBookToMe;
    private javax.swing.JLabel getnome;
    private javax.swing.JLabel imageBook;
    private javax.swing.JTextField inputSearch;
    private javax.swing.JLabel isbnB;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JPopupMenu jPopupMenu3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel localB;
    private javax.swing.JLabel localBook;
    private javax.swing.JLabel localBook1;
    private javax.swing.JTextField name;
    private javax.swing.JTextField newPassword;
    private javax.swing.JLabel okayOff;
    private javax.swing.JLabel okayOn;
    private javax.swing.JTextField password;
    private javax.swing.JTabbedPane profile;
    private javax.swing.JPanel profileBook;
    private javax.swing.JTextField room;
    private javax.swing.JButton saveButton;
    private javax.swing.JButton saveData;
    private javax.swing.JButton search;
    private javax.swing.JList searchResults;
    private javax.swing.JList searchResultsAcervo;
    private javax.swing.JList searchResultsUsers;
    private javax.swing.JPanel searchTab;
    private javax.swing.ButtonGroup searchType;
    private javax.swing.JLabel succeededDataUpdateMessage;
    private javax.swing.JLabel teacherB;
    private javax.swing.JLabel teacherBook;
    private javax.swing.JRadioButton title;
    private javax.swing.JLabel titleB;
    private javax.swing.JPanel upToolbar;
    private javax.swing.JPanel userProfileTab;
    private javax.swing.JLabel welcome;
    // End of variables declaration//GEN-END:variables

    private String[] setListInSearchResultuser(){
        int i = 0;
        String[] list;
        if (searchListUsers == null) {
            list = new String[1];                        
        }
        else{
            list = new String[searchListUsers.size()];
        }
        
        for (User user : searchListUsers) {
            if (!(user.getEmail().equals(Lendbook.user.getEmail()))) {
                list[i] = i+1 + " - "+user.getName();
                i++;                
            }
                        
        }
        return list;        
    }
    
    private void modelAuxSetUser(){
        
        searchResultsUsers.setModel(new javax.swing.AbstractListModel() {
            String[] strings = setListInSearchResultuser();
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
            });        
    }
    
    private void setAcervoUser(){
        searchListUsers = Lendbook.system.getController().getUsers();
        modelAuxSetUser();
        
    }
}
