/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Window;

import Code.Book;
import System.Lendbook;
import javax.swing.*;
        
/**
 *
 * @author gabrieljrr
 */
public class BookRegister extends SwitchablePanel {

    /**
     * Creates new form BookRegister
     */
    public BookRegister(Window frame) {
         super(frame);
        initComponents();
    }
     

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleText = new javax.swing.JTextField();
        authorText = new javax.swing.JTextField();
        generText = new javax.swing.JTextField();
        ISBNText = new javax.swing.JTextField();
        publisherText = new javax.swing.JTextField();
        photoCoverLabel = new javax.swing.JLabel();
        searchCoverButton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        registerButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titleText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                titleTextActionPerformed(evt);
            }
        });
        add(titleText, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 390, 229, 30));
        add(authorText, new org.netbeans.lib.awtextra.AbsoluteConstraints(455, 158, 229, 30));
        add(generText, new org.netbeans.lib.awtextra.AbsoluteConstraints(455, 241, 229, 30));
        add(ISBNText, new org.netbeans.lib.awtextra.AbsoluteConstraints(455, 319, 229, 30));
        add(publisherText, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 400, 229, -1));

        photoCoverLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ImageIcon image = new ImageIcon("/Images/defaultBookCover.png");
        photoCoverLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(photoCoverLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 160, 220));

        searchCoverButton.setText("...");
        searchCoverButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchCoverButtonActionPerformed(evt);
            }
        });
        add(searchCoverButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, 30, -1));

        jLabel8.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 140));
        jLabel8.setText("Capa:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, -1, -1));

        jLabel6.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 140));
        jLabel6.setText("Editora:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 360, -1, -1));

        jLabel5.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 140));
        jLabel5.setText("ISBN:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 290, -1, -1));

        jLabel4.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 140));
        jLabel4.setText("Título: ");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 360, -1, -1));

        jLabel3.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 140));
        jLabel3.setText("Autor:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 130, -1, -1));

        jLabel2.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 140));
        jLabel2.setText("Gênero:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 210, -1, -1));

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/sair.png"))); // NOI18N
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 500, 50, -1));

        registerButton.setFont(new java.awt.Font("DialogInput", 1, 18));
        registerButton.setForeground(new java.awt.Color(-16746496,true));
        registerButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/registericon.png"))); // NOI18N
        registerButton.setText("Cadastrar!");
        registerButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerButtonMouseClicked(evt);
            }
        });
        registerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButtonActionPerformed(evt);
            }
        });
        add(registerButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 460, 184, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cadastro.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void searchCoverButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchCoverButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchCoverButtonActionPerformed

    private void titleTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_titleTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_titleTextActionPerformed
   private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {                                               
      
 
    } 
    private void registerButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerButtonMouseClicked

        int nextId = Lendbook.system.getController().getBooks().size()+1;
        String msg = "Cadastro realizado com sucesso!";                          
        try{
            if(ISBNText.getText().equals("")){
                throw new Exception("Campo Vazio");
            }
            if(ISBNText.getText().length()!= 10 && ISBNText.getText().length()!= 13){
                throw new Exception("O ISBN deve conter 10 ou 13 dígitos.");
            }
            Lendbook.system.add(new Book(titleText.getText(),Lendbook.user.getEmail(),authorText.getText(),Integer.parseInt(ISBNText.getText()),publisherText.getText(),generText.getText(),nextId));
            getMainFrame().switchPanels(new BookRegister(getMainFrame()));
        }catch (Exception e){
            msg = e.getMessage();
        }finally{            
            JOptionPane.showMessageDialog(this,msg);
        } 
    }//GEN-LAST:event_registerButtonMouseClicked

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        getMainFrame().switchPanels(new Aplication(getMainFrame()));
    }//GEN-LAST:event_backActionPerformed

 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ISBNText;
    private javax.swing.JTextField authorText;
    private javax.swing.JButton back;
    private javax.swing.JTextField generText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel photoCoverLabel;
    private javax.swing.JTextField publisherText;
    private javax.swing.JButton registerButton;
    private javax.swing.JButton searchCoverButton;
    private javax.swing.JTextField titleText;
    // End of variables declaration//GEN-END:variables
}
